---

- name: Start Nginx
  service: 
    name: nginx 
    state: started
  become: yes

- name: Reload Nginx
  service: 
    name: nginx 
    state: reloaded
  become: yes

- name: Enable ufw
  ufw:
    state: enabled