---
# This playbook contains common plays that will be run on all nodes.

- name: Ensure a list of common packages is present
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - vim
    - unzip
  become: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes

# Ensure that pip is installed

- name: Check to see if pip is already installed
  command: "pip3 --version"
  ignore_errors: true
  register: pipisinstalled
  changed_when: false

- name: Download get-pip.py
  get_url: 
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp
    validate_certs: no
  register: pipdownloaded
  when: pipisinstalled is failed

- name: Install pip3
  command: "python3 /tmp/get-pip.py"
  when: pipisinstalled is failed and pipdownloaded is succeeded
  register: pipinstalled
  become: yes

- name: Delete get-pip.py
  file: 
    state: absent 
    path: /tmp/get-pip.py
  when: pipisinstalled is failed and pipinstalled is succeeded