---
# This playbook contains common plays that will be run on all nodes.

- name: Ensure a list of common packages is present
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - vim
    - unzip
  become: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes