---
# This playbook initializes snort

- name: Restart Snort
  service:
    name: snort
    state: restarted
  become: yes

- name: Restart Snortd
  service:
    name: snortd
    state: restarted
  become: yes
