---
# This playbook contains plays that will be run on web server.

- name: Ensure ngingx is present
  apt: 
    name: nginx
    state: present 
    update_cache: true
  register: nginx
  notify:
    - Start Nginx
  become: yes

- name: Change presentation page
  when: nginx is succeeded
  template:
    src: index.html
    dest: /var/www/html/index.html
  notify:
    - Reload Nginx
  become: yes