---
# This playbook deploys the whole application stack in this infrastructure.

- name: Apply common configuration to all nodes
  hosts: all
  remote_user: root

  roles:
    - common

- name: Configure and deploy the webservers
  hosts: webservers
  remote_user: root

  roles:
    - web

- name: Configure and deploy the vulnerable clients
  hosts: clients
  remote_user: root

  roles:
    - vulnerable