---
# This playbook contains plays that will be run on the ips node.

- name: Updating apt-cache
  apt:
    update_cache: yes
    cache_valid_time: 86400
  become: yes

- name: Installing iproute
  apt:
    name: iproute
    state: present
  become: yes
  when: >
    ansible_distribution != "Ubuntu" or
    (ansible_distribution == "Ubuntu" and
    ansible_distribution_major_version < "18")

- name: Installing iproute2
  apt:
    name: iproute2
    state: present
  become: yes
  when: >
    ansible_distribution == "Ubuntu" and
    ansible_distribution_major_version >= "18"

- name: Installing pre-reqs
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - build-essential
    - ethtool
    - flex
    - libpcap-dev
    - libpcre3-dev
    - libdumbnet-dev
    - zlib1g-dev

- name: Download and Install Snort
  apt:
    name: snort
    state: present
  register: download_snort
  ignore_errors: yes
  become: yes

- name: Configure Snort
  template:
    src: "snort.conf.j2"
    dest: /etc/snort/snort.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: Restart Snort

- name: Configuring Snort Daemon
  template:
    src: "snort.debian.conf.j2"
    dest: "/etc/snort/snort.debian.conf"
    owner: root
    group: root
    mode: 0600
  become: yes
  notify: Restart Snort

- name: Ensuring directories exists
  file:
    dest: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
    recurse: yes
  become: yes
  with_items:
    - "/usr/lib/snort_dynamicrules"
    - "/usr/lib/snort_dynamicengine"
    - "/usr/lib/snort_dynamicpreprocessor"
  when: >
    ansible_distribution_release == "precise" or
    ansible_distribution_release == "wheezy"

- name: Import Snort Rules
  template:
    src: "{{ item }}"
    dest: "/etc/snort/rules"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "rules/white_list.rules"
    - "rules/black_list.rules"
    - "rules/local.rules"
  become: yes

- name: Validate Snort Configuration
  become: yes
  command: "/usr/sbin/snort -T -i eth0:eth1 -c /etc/snort/snort.conf"
  register: snort_validation
  notify:
    - Restart Snort
