---
# This playbook contains plays that will be run on client (vulnerable) nodes.
- include: users.yml

- name: Ensure python 3 is present
  apt: 
    name: python
    state: present 
    update_cache: true
  become: yes
- name: Install a list of packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - python3-setuptools
    - python3-dev
    - build-essential
    - nmap
    - telnet
    - telnetd
    - socat
  become: yes

# Install Python3 packages

- name: Install a list of python packages, force upgrade
  pip:
    name: "{{ packages }}"
    state: latest
  #when: pipisinstalled is succeeded or pipinstalled is succeeded
  vars:
    packages:
    - virtualenv
    - python-nmap
    - ifaddr
  become: yes
